In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
A = np.random.randn(10)
A

array([ 0.73916009, -1.14955014,  1.11695218, -1.19007465,  0.37201627,
        1.10671114,  0.40152329,  1.81461042, -0.15814985, -1.02090804])

In [6]:
B = np.random.randn(10)
B

array([ 0.23714855, -2.02130057, -0.90269646, -1.04402815,  0.13058107,
        1.13282087,  1.41672738,  0.08514922, -0.42429624,  0.79043595])

In [7]:
# Binary Functions
np.add(A,B)

array([ 0.97630863, -3.17085071,  0.21425573, -2.2341028 ,  0.50259734,
        2.23953201,  1.81825067,  1.89975964, -0.58244609, -0.23047209])

In [8]:
np.maximum(A,B)

array([ 0.73916009, -1.14955014,  1.11695218, -1.04402815,  0.37201627,
        1.13282087,  1.41672738,  1.81461042, -0.15814985,  0.79043595])

In [10]:
website = 'https://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True