In [6]:
import numpy as np

In [7]:
my_list1 = [1,2,3,4]

In [9]:
my_array1 = np.array(my_list1)

In [11]:
my_array1

array([1, 2, 3, 4])

In [12]:
my_list2 = [11,22,33,44]

In [14]:
my_lists = [my_list1, my_list2]

In [15]:
my_array2 = np.array(my_lists)

In [16]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [17]:
my_array2.shape

(2, 4)

In [18]:
my_array2.dtype

dtype('int64')

In [19]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.arange